---
abstract: 'Interface for the Shodan Computer Search Engine API'
author:
  - 'Dudley Adams <dudleyadams@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WWW-Shodan-API
requires:
  Carp: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  URI::Escape: '0'
  constant: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.002'
